// Apache configuration for the Hostinger-hosted landing-page domains.
//
// _redirects and _headers are a Cloudflare Pages format. On Apache they do
// nothing at all, and Apache will happily serve them as plain text to anyone
// who requests /_headers — so the Apache builds get this file instead and the
// Pages files are deleted from the output.
//
// Everything here is the Apache equivalent of what public/_headers and
// scripts/site-files.mjs produce for Cloudflare, so the two hosts serve the
// same headers, the same redirects and the same 404 behaviour.

const TEXT_FILES = ["robots.txt", "ai.txt", "llms.txt", "llms-full.txt", "humans.txt", "security.txt"];
const JSON_FILES = ["ai.json", "agents.json", "manifest.json", "agent-card.json", "tdmrep.json"];

const escapeForFilesMatch = (name) => name.replace(/\./g, "\\.");

/**
 * @param {object} options
 * @param {string} options.domain
 * @param {string} options.target
 * @param {[string, string][]} options.redirects  path pairs, e.g. [["/trial", "/"]]
 */
export function renderHtaccess({ domain, target, redirects }) {
  const redirectRules = redirects.map(([from, to]) => {
    // RewriteRule patterns are matched against the path with no leading slash.
    // "/?" so the trailing-slash shape ad URLs arrive in redirects too, rather
    // than falling through to the 404 page.
    const pattern = `^${from.replace(/^\//, "")}/?$`;
    return `  RewriteRule ${pattern} ${to} [R=301,L]`;
  });

  return `# Generated by scripts/site-files.mjs — do not edit by hand.
# Deployment: ${domain} (target "${target}")
#
# Apache/Hostinger equivalent of the _headers and _redirects files this project
# uses on Cloudflare Pages. Upload the whole folder's contents into public_html.

# Apache would otherwise try to guess that /foo means /foo.html, which makes the
# URL the page is served at ambiguous. This deployment has exactly one page and
# a 404, so guessing can only cause surprises.
Options -MultiViews
DirectoryIndex index.html

# Serve the prerendered 404 snapshot with a real 404 status. It still boots the
# SPA, so a deep link renders the app's own not-found page rather than a bare
# Apache error. Without this, unknown URLs would return Apache's default page
# and crawlers would see none of the site's markup.
ErrorDocument 404 /404.html

<IfModule mod_rewrite.c>
  RewriteEngine On

  # Force HTTPS. The X-Forwarded-Proto check is what prevents a redirect loop on
  # shared hosting, where TLS is terminated in front of Apache and the request
  # reaches it as plain HTTP.
  RewriteCond %{HTTPS} !=on
  RewriteCond %{HTTP:X-Forwarded-Proto} !=https
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

  # Consolidate www onto the bare domain, which is what the page's canonical
  # declares. Without this the same page answers on two hostnames.
  RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]
  RewriteRule ^ https://%1%{REQUEST_URI} [R=301,L]

  # Retired paths. This page lived at ${redirects[0]?.[0] ?? "/"} before it had its own
  # domain; ads, QR codes and bookmarks pointing there must not start 404ing.
${redirectRules.join("\n")}
</IfModule>

<IfModule mod_headers.c>
  # ── Site-wide security headers ─────────────────────────────────────────────
  Header always set X-Content-Type-Options "nosniff"
  Header always set Referrer-Policy "strict-origin-when-cross-origin"
  Header always set X-Frame-Options "SAMEORIGIN"
  Header always set Permissions-Policy "geolocation=(), microphone=(), camera=(), interest-cohort=()"
  Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"

  # ── Build output ───────────────────────────────────────────────────────────
  # Content-hashed filenames, so a one-year immutable cache can never go stale.
  <FilesMatch "\\.(js|css|png|jpg|jpeg|gif|webp|svg|ico|woff|woff2|pdf)$">
    Header set Cache-Control "public, max-age=31536000, immutable"
  </FilesMatch>

  # HTML must never be long-cached or a redeploy would not reach returning
  # visitors — the filenames do not change.
  <FilesMatch "\\.html$">
    Header set Cache-Control "public, max-age=0, must-revalidate"
  </FilesMatch>

  # ── Crawler- and agent-facing documents ────────────────────────────────────
  # Short cache so an edit propagates in minutes, CORS open so answer engines
  # can fetch them from a browser context, X-Robots-Tag: all so nothing
  # inherited keeps them out of an index.
  <FilesMatch "^(${TEXT_FILES.map(escapeForFilesMatch).join("|")})$">
    Header set Content-Type "text/plain; charset=utf-8"
    Header set Access-Control-Allow-Origin "*"
    Header set X-Robots-Tag "all"
    Header set Cache-Control "public, max-age=300, must-revalidate"
  </FilesMatch>

  <FilesMatch "^(${JSON_FILES.map(escapeForFilesMatch).join("|")})$">
    Header set Content-Type "application/json; charset=utf-8"
    Header set Access-Control-Allow-Origin "*"
    Header set X-Robots-Tag "all"
    Header set Cache-Control "public, max-age=300, must-revalidate"
  </FilesMatch>

  <FilesMatch "^sitemap\\.xml$">
    Header set Content-Type "application/xml; charset=utf-8"
    Header set Access-Control-Allow-Origin "*"
    Header set X-Robots-Tag "all"
    Header set Cache-Control "public, max-age=300, must-revalidate"
  </FilesMatch>
</IfModule>

# Some shared hosts do not know these types and fall back to
# application/octet-stream, which makes the browser download the file instead of
# rendering it. Declaring them costs nothing where they are already correct.
<IfModule mod_mime.c>
  AddType image/webp .webp
  AddType image/svg+xml .svg
  AddType font/woff2 .woff2
  AddType font/woff .woff
  AddType application/json .json
  AddType text/plain .txt
</IfModule>

# .well-known must stay reachable: it carries agent-card.json, tdmrep.json and
# security.txt. Some hosting panels ship a rule that hides dot-directories.
<IfModule mod_rewrite.c>
  RewriteRule ^\\.well-known/ - [L]
</IfModule>

<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml application/javascript application/json image/svg+xml
</IfModule>
`;
}
