// Post-build pass that writes the Cloudflare Pages routing file and adapts the
// crawler-facing files to the deployment target. Runs after `vite build` and
// before (or after — order does not matter) prerender.
//
// Deliberately conservative on the main target: it writes _redirects and then
// only *verifies* robots.txt and sitemap.xml rather than regenerating them.
// Those two files are hand-tuned and were live on Vercel; regenerating them
// during an infrastructure migration would mix an SEO change into a move that
// is supposed to change nothing. The landing-page targets are new deployments
// with no history to preserve, so there they are rewritten.
import { readFile, writeFile, rm, access } from "node:fs/promises";
import path from "node:path";
import { currentSiteUrl, currentTarget, targetConfig } from "./deployTargets.mjs";

const DIST = "dist";
const TARGET = currentTarget();
const SITE_URL = currentSiteUrl();
const config = targetConfig(TARGET);

const exists = (file) => access(file).then(() => true, () => false);

// ── _redirects ───────────────────────────────────────────────────────────────
// Cloudflare Pages evaluates _redirects BEFORE it looks for a matching asset:
// "Redirects are always followed, regardless of whether or not an asset matches
// the incoming request." That makes the usual SPA line — `/* /index.html 200` —
// actively harmful here. It would shadow every prerendered snapshot, so
// /services, /trial and /landingpage would all serve the HOME PAGE's HTML to
// any crawler that does not run JavaScript: same title, same canonical, same
// JSON-LD on every URL. The site would still look correct in a browser, which
// is exactly what makes it dangerous.
//
// So there is no catch-all here. Unmatched URLs fall through to dist/404.html,
// which prerender.mjs generates and which still boots the SPA.
async function writeRedirects() {
  // prerender.mjs writes each route as dist/<route>.html so Cloudflare serves
  // it at the unslashed URL the page's canonical claims. The consequence is
  // that "/trial/" matches no asset and would fall through to the 404 page.
  // It must not: ad URLs arrive in whatever shape they were pasted into the ad
  // platform, the slashed shape used to return 200 on Vercel, and it has
  // already caused one live bug on these exact pages (see src/App.tsx).
  //
  // These rules also make the slashed form *consolidate* onto the canonical
  // instead of serving a duplicate 200 the way Vercel did — a small SEO gain
  // that comes free with the migration.
  const slashRules = config.routes
    .filter((route) => route !== "/")
    .map((route) => [`${route}/`, route]);

  const rules = [...slashRules, ...config.redirects];

  const lines = [
    "# Generated by scripts/site-files.mjs — do not edit by hand.",
    `# Deploy target: ${TARGET}`,
    "#",
    "# No `/* /index.html 200` line on purpose: Cloudflare applies redirects",
    "# before asset matching, so a catch-all rewrite would serve the home page's",
    "# prerendered HTML for every route. Unmatched paths use dist/404.html.",
    "",
    "# Trailing-slash consolidation onto the canonical (unslashed) URL.",
    ...slashRules.map(([from, to]) => `${from}    ${to}    301`),
    "",
    "# Retired paths.",
    ...config.redirects.flatMap(([from, to]) => [
      `${from}    ${to}    301`,
      `${from}/    ${to}    301`,
    ]),
    "",
  ];
  await writeFile(path.join(DIST, "_redirects"), lines.join("\n"), "utf-8");
  console.log(`_redirects written (${rules.length} rules)`);
}

// ── robots.txt / sitemap.xml ─────────────────────────────────────────────────
async function verifyMainCrawlerFiles() {
  const problems = [];

  const robots = await readFile(path.join(DIST, "robots.txt"), "utf-8");
  for (const required of [`Sitemap: ${SITE_URL}/sitemap.xml`, `Policy: ${SITE_URL}/ai.json`]) {
    if (!robots.includes(required)) problems.push(`robots.txt is missing "${required}"`);
  }

  // Drift guard: the sitemap is hand-maintained, and the set of pages that
  // should be in it is declared in deployTargets.mjs. If someone adds a page
  // and forgets the sitemap (or lists a noindex landing page in it), this
  // fails the build instead of quietly shipping a contradictory signal.
  const sitemap = await readFile(path.join(DIST, "sitemap.xml"), "utf-8");
  const listed = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
  const expected = config.indexable.map((p) => (p === "/" ? `${SITE_URL}/` : `${SITE_URL}${p}`));

  for (const url of expected) {
    if (!listed.includes(url)) problems.push(`sitemap.xml is missing ${url}`);
  }
  for (const url of listed) {
    if (!expected.includes(url)) problems.push(`sitemap.xml lists an unexpected URL: ${url}`);
  }

  if (problems.length) {
    throw new Error(`Crawler file check failed:\n  - ${problems.join("\n  - ")}`);
  }
  console.log(`robots.txt and sitemap.xml verified (${listed.length} indexable URLs)`);
}

// The landing-page domains host one noindex page each. They get a robots.txt
// that keeps them fully crawlable — ad quality reviewers and link-preview
// scrapers must be able to fetch them — but no sitemap, because a sitemap
// listing a noindex URL is a contradictory signal to Google.
async function writeLandingCrawlerFiles() {
  const robots = [
    `# robots.txt — ${SITE_URL}`,
    "#",
    "# Single-page paid-traffic domain. The page carries a page-level noindex,",
    "# so it is intentionally left fully crawlable: ad quality reviewers and",
    "# link-preview scrapers must be able to fetch it. No sitemap is published,",
    "# because listing a noindex URL contradicts the page-level directive.",
    "#",
    "# The brand's crawler-facing documents stay on the main domain, which is",
    "# where the content they describe actually lives.",
    "",
    "User-agent: *",
    "Allow: /",
    "",
    "Policy: https://llamamaps.com/ai.json",
    "LLMs: https://llamamaps.com/llms.txt",
    "",
  ].join("\n");
  await writeFile(path.join(DIST, "robots.txt"), robots, "utf-8");

  const sitemap = path.join(DIST, "sitemap.xml");
  if (await exists(sitemap)) await rm(sitemap);

  // manifest.json ships shortcuts to /services and /contacts. Those pages do
  // not exist on a landing-page domain, so installing the PWA there would give
  // the user two shortcuts that land on a 404.
  const manifestPath = path.join(DIST, "manifest.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf-8"));
  delete manifest.shortcuts;
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf-8");

  console.log("robots.txt rewritten, sitemap.xml removed, manifest shortcuts stripped");
}

async function main() {
  console.log(`site-files: target="${TARGET}" site="${SITE_URL}"`);
  await writeRedirects();

  if (TARGET === "main") {
    await verifyMainCrawlerFiles();
  } else {
    await writeLandingCrawlerFiles();
  }

  if (!(await exists(path.join(DIST, "_headers")))) {
    throw new Error("dist/_headers is missing — public/_headers did not make it into the build.");
  }
  console.log("site-files: done");
}

main().catch((err) => {
  console.error("site-files failed:", err.message);
  process.exit(1);
});
